const items = [
  {
    id: 1,
    title: "Akara and Pap",
    category: "breakfast",
    price: 15.99,
    img: "./images/dinner8.webp",
    desc: `Moin-Moin and Akara are both meals made from pureed beans and spicy ingredients, full of proteins, light and refreshing. There's just something about Akara and Moin-Moin that makes them perfect for breakfast. `,
  },
  {
    id: 2,
    title: "Jollof rice",
    category: "lunch",
    price: 13.99,
    img: "./images/lunch1.jpg",
    desc: `Nigerian Jollof Rice or Jellof rice is a rich and incredibly tasty west African one-pot Meal. It is a very versatile dish, and it is usually made from scratch using Rice, Tomatoes, Pimento peppers, Tomato paste, Scotch bonnet, Onions, Salt, and other spices.`,
  },
  {
    id: 3,
    title: "Plaintain and Fish stew",
    category: "dinner",
    price: 6.99,
    img: "./images/diner1.jpg",
    desc: `Deliciously charred plantains are the star of this hearty and tasty, plant-based, Roasted Plantain Bean Stew you will love.`,
  },
  {
    id: 4,
    title: "ewa Agoyin - Beans",
    category: "breakfast",
    price: 20.99,
    img: "./images/breakfast3.jpeg",
    desc: `Bread and beans or Ewa agoyin is native to the Yoruba people but it is also one of the foods every struggling Nigerian knows well. `,
  },
  {
    id: 5,
    title: "Sea food okro",
    category: "lunch",
    price: 22.99,
    img: "./images/lunch2.jpg",
    desc: `This Nigerian seafood okra is best eaten by itself and is prepared differently from the okro soup recipe, which can be eaten with fufu.`,
  },
  {
    id: 6,
    title: "Plaintain and Vegetable",
    category: "dinner",
    price: 18.99,
    img: "./images/dinner7.jpg",
    desc: `Boiled plantain and vegetable sauce is one of the most popular of recent trending foods on earth. It is easy, it is quick, it tastes yummy`,
  },
  {
    id: 7,
    title: "Yam and Egg stew",
    category: "breakfast",
    price: 8.99,
    img: "./images/breakfast1.jpg",
    desc: `Nigerian Egg Stew is a popular Nigerian Stewed eggs recipe. Egg stew is very easy to make and is a staple in most Nigerian homes. It is particularly eaten at breakfast and is enjoyed with boiled Yam. `,
  },
  {
    id: 8,
    title: "Stir fry spaghetti",
    category: "lunch",
    price: 12.99,
    img: "./images/lunch3.jpg",
    desc: `Jollof spaghetti is a delicious alternative to everyday Nigerian Jollof rice. This recipe is incredibly delicious and cooks faster. Perfect for lunch.`,
  },
  {
    id: 9,
    title: "Yam pepper soup",
    category: "dinner",
    price: 16.99,
    img: "./images/dinner3.jpg",
    desc: `Yam and Fresh Fish Pepper Soup is one of the easiest Nigerian food to prepare. It is a bit spicy but undeniably, a delicious meal for any time of the day.`,
  },
  {
    id: 10,
    title: "Indomie noodles",
    category: "breakfast",
    price: 12.99,
    img: "./images/breakfast5.jpeg",
    desc: `Indomie is an extremely popular instant noodle brand in Nigeria, so popular that it has become the household name for all instant noodles. People can get very creative when preparing Indomie, and usually pair it with fried or boiled egg. `,
  },
  {
    id: 11,
    title: " efo riro - Vegetable soup",
    category: "lunch",
    price: 13.99,
    img: "./images/lunch6.webp",
    desc: `This vegetable soup recipe is so flavorful and easy to make! It's packed with vegetables and can be eaten with swallow or rice.`,
  },
  {
    id: 12,
    title: "Amala and ewedu with gbegiri - Abula",
    category: "lunch",
    price: 13.99,
    img: "./images/lunch7.jpg",
    desc: `Àbùlà is a soup of Yoruba people from Western Nigeria. It is typically eaten together with Amala, but can be eaten with other swallow foods. Abula is a mixture of Gbegiri, Ewedu and ọbẹ̀ ata.`,
  },
  {
    id: 13,
    title: "Abacha - African Salad",
    category: "dinner",
    price: 16.99,
    img: "./images/dinner4.jpeg",
    desc: `African salad (Abacha food) is a delicious west African food that is native to the ndi Igbo (people of Igbo).`,
  },
  {
    id: 14,
    title: "Moin moin ",
    category: "dinner",
    price: 16.99,
    img: "./images/dinner6.jpg",
    desc: `Moimoi is an outstanding dish in Nigeria. It’s one of the Nigerians best delicacies. It’s a steamed beans pudding with a mixture of beans and other ingredients, it can be enjoyed as a main dish or as a side dish to other menus such as Jollof Rice, Fried rice, pap..`,
  },
];
export default items;
